config/routes.rb
Rails.application.routes.draw do
  devise_for :buyers, controllers: { registrations: "registrations" }
  get 'static_pages/team'
  get 'static_pages/contact'
  root :to => "static_pages#home"
  get "/fetch_offers" => 'offers#from_category', as: 'fetch_offers'
  resources :offers, only: [:index] do
    resources :transactions
  end
  resources :buyers, only: [:show, :edit, :update]
  resource :messages do
    collection do
      post 'start'
      post 'confirm'
    end
  end
  resources :carts, only: [:show, :create, :edit]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def show
        @transactions = current_buyer.transactions.where(payment_confirmation:false)
        prices = []
        @transactions.each do |x|
           prices << x.offer.offer_price * x.transa_quantity
        $total_price = prices.sum
        end
    end

    def create
        @price_paid=$total_price
        boot_stripe
        $total_price=0
        @transactions = current_buyer.transactions.where(payment_confirmation:false)
        @transactions.each do |transa|
            transa.update(payment_confirmation:true)

          boot_twilio
          @client.messages.create ({
          from: Rails.application.credentials.twilio_number,
          to: transa.offer.farmer.phone_number,
          body: "Un acheteur souhaite #{transa.transa_quantity}kilos de #{transa.offer.product.prod_subname} pour #{transa.offer.offer_price} par kilo. Pour accepter tapez Y#{transa.id} pour refuser tapez N#{transa.id}"
          })
          transa.offer.farmer.count = 4
          transa.offer.farmer.save
        end
        flash[:primary] = "Produit(s) commandé(s), en attente confirmation producteur"
    end

    private
 
    def boot_twilio
      account_sid = Rails.application.credentials.twilio_sid
      auth_token = Rails.application.credentials.twilio_token
      @client = Twilio::REST::Client.new account_sid, auth_token
    end


    def boot_stripe
      customer = Stripe::Customer.create({
        email: params[:stripeEmail],
        source: params[:stripeToken],})

      charge = Stripe::Charge.create({
        customer: customer.id,
        amount: @price_paid.to_i,
        description: 'Rails Stripe customer',

        currency: 'eur',
      })
    
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to cart_path(current_buyer.id)
    end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_item.html.erb
<% if @transactions.size > 0 %>
	<% @transactions.each do |item| %>
		<div class="card">
			<header class="card-header">
				<p class="card-header-title">
				<h3><%= item.offer.product.prod_name %> #<%= item.offer.id%> :

				<%= (item.offer.offer_price * item.transa_quantity)/10%>€</h3>
				</p>
				<a link_to ="#" class="card-header-icon" aria-label="more options">
				<span class="icon">
					<i class="fas fa-angle-down" aria-hidden="true"></i>
				</span>
				</a>
			</header>
			<div class="card-content column is-flex">
				<div class="pull-left column">
					<div class="product-card w-inline-block">
						<div class="offer-recap card-content">
							<h4> Informations sur le vendeur </h4>
							<ul> Adresse : <%= item.offer.offer_adress%></ul>
							<ul> Code postal : <%= item.offer.offer_zipcode%></ul>
							<ul> Ville : <%= item.offer.offer_city %></ul>
							<ul> Pays : <%= item.offer.offer_country %></ul>
							<ul> Date de récolte : <%=item.offer.date_harvest.to_date.to_formatted_s(:long)%></ul>
						</div>
					</div>
				</div>
				<div class ="pull-right column">
					<div class ="product-card w-inline-block">
						<div class="transa-recap card-content">
							<h4> Récapitulatif de la transaction </h4>
							<ul> Adresse : <%= item.transa_adress%></ul>
							<ul> Code Postal : <%= item.transa_zipcode%></ul>
							<ul> Quantité : <%= item.transa_quantity%> kg</ul>
							<ul> Date de rencontre : <%= item.transa_date.to_date.to_formatted_s(:long)%></ul>
							<ul> Ville : <%= item.transa_city%></ul>
							<ul> Statut de la commande : <% if item.transa_confirmation == false %> En attente <% else %> Validée<% end %></ul>
						</div>
					</div>
				</div>
			</div>
			<a class="button is-primary is-outlined" href="<%=offer_transaction_path(item.offer.id,item.id)%>" role="button" data-confirm="Etes-vous sur?" data-method="DELETE" >Retirer du panier</a>
		</div>
		<div></div>	  	
	<% end %>
	<h2><%= render "carts/stripe" %></h1>
<% else %>
<div class="section-5">
	<div class="container-2 w-container">
		<div class="product">
			<div class="container">
				<div class="row">
					<div class="col-md-6 offset-md-3">
						<div id="empty_cart">
							<h2> Votre panier est vide </h2><br><br><br>
							<%= link_to "Acheter", offers_path, class: "tag is-medium is-primary"%>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/carts/_stripe.html.erb
<%= form_tag carts_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <label class="amount">
        <span>Total: €<%=$total_price/10%> </span>
      </label>
    </article>
  
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="Amount : €<%=$total_price/10%>"
            data-amount='<%= $total_price *10%>'
            data-currency="eur"
            data-locale="auto"></script>
  <% end %>

app/views/carts/create.html.erb
<div class="section-5">
<div class="container-2 w-container">
<div class="product">
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
<h2>Merci pour votre achat, vous allez recevoir les instructions par email !</h2>
</div></div></div></div></div>

app/views/carts/show.html.erb
<div class="cart_item">
	<%= render partial: "cart_item" %>
</div>