config/routes.rb
Rails.application.routes.draw do
  devise_for :buyers, controllers: { registrations: "registrations" }
  get 'static_pages/team'
  get 'static_pages/contact'
  root :to => "static_pages#home"
  get "/fetch_offers" => 'offers#from_category', as: 'fetch_offers'
  resources :offers, only: [:index] do
    resources :transactions
  end
  resources :buyers, only: [:show, :edit, :update]
  resource :messages do
    collection do
      post 'start'
      post 'confirm'
    end
  end
  resources :carts, only: [:show, :create, :edit]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :transactions

  validates :first_name, presence:true, on: :update
  validates :last_name, presence:true, on: :update
  validates :buyer_zipcode, presence:true, on: :update
  validates :buyer_adress, presence:true, on: :update
  validates :buyer_city, presence:true, on: :update
  validates :buyer_country, presence:true, on: :update
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  before_action :authenticate_buyer!

  def show
  end
  
  def edit
    @buyer = current_buyer
  end

  def update
    @buyer = current_buyer
    if @buyer.update(buyer_update)
      flash[:success] = "Profil mis à jour"
      redirect_to @buyer
    else
      render 'edit'
    end
  end

  private
  def buyer_update
    params.require(:buyer).permit(:first_name, :last_name, :buyer_adress,:buyer_city,:buyer_country,:buyer_zipcode, buyer: current_buyer)
  end
 
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/views/buyers/edit.html.erb
<ul>
  <% if @buyer.errors.any? %>                      
    <p>Nous n'avons pas réussi à modifier le potin pour la (ou les) raison(s) suivante(s) :</p>
    <% @buyer.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
</ul>


<div></div>
<div class="section-5">
<div class="container-2 w-container">
<div class="product">
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
          <h1 class="heading-3">Mettre à jour mon profil</h1> <br/></br>
          <div class="w-form">

          <%= form_for @buyer do |f| %>

            <%= f.label :Prénom %>
            <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", class: "input" %><br/></br>
            <%= f.label :Nom %>
            <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", class: "input" %><br/></br>

            <%= f.label :code_postal %>
            <%= f.text_field :buyer_zipcode, autofocus: true, autocomplete: "buyer_zipcode", class: "input" %><br/></br>
            
            <%= f.label :Adresse %>
            <%= f.text_field :buyer_adress, autofocus: true, autocomplete: "buyer_adress", class: "input" %><br/></br>

            <%= f.label :Ville %>
            <%= f.text_field :buyer_city, autofocus: true, autocomplete: "buyer_city", class: "input" %><br/></br>

            <%= f.label :Pays %>
            <%= f.text_field :buyer_country, autofocus: true, autocomplete: "buyer_country", class: "input" %></br>

            <div class="actions">
            <%= f.submit "Enregistrer", class: "button small w-button" %>
          </div>
                                  
          <% end %>
          
          </div>
        </div>
      </div>
    </div>
  </div>
  </div></div></div></div></div>

app/views/buyers/show.html.erb
  <div class="section-5">
    <div class="container-2 w-container">
      <div class="product">
        <div class="product-info">
          <h1 class="heading-3"><%= current_buyer.first_name%> <%= current_buyer.last_name%></h1>
          <p class="text-grey"><%= current_buyer.buyer_adress%>, <%= current_buyer.buyer_zipcode%>, <%= current_buyer.buyer_city%> -<%= current_buyer.buyer_country%></p>
          <a href="<%=edit_buyer_path%>" class="button small ghost w-button">Editer le profil</a>
          <br/>
          <a href="<%=edit_buyer_registration_path%>" class="text-grey">Modifier mes identifiants</a>
        </div>
      </div>
  </div>

  <div class="container w-container">
    <div class="wrapper">
      <div class="shop-header">
        <h3 class="heading-7">Commandes en cours</h3>
        <div class="shop-header-line">
          <div class="shop-header-color"></div>
        </div>
      </div>
    </div>

    <div class="columns w-row tabcontent">
      <div class="columns  is-multiline">
      <%current_buyer.transactions.each do |transa|%>
        <%if transa.payment_confirmation ==true %>
          <div class="column is-one-third">
            <div class="product-card w-inline-block">
                <div class="product-card-image-wrapper"><img width="99" src="https://uploads-ssl.webflow.com/5d7e3127cad5177918ca3737/5d7e49b0a3db08f53036d9b4_lemon.svg" alt=""></div>
                <div class="card-content">
                  <h4 class="product-card-heading"><%=transa.offer.product.prod_name%></h4>
                  <h6 class="paragraph-2">Quantité commandée: <%=transa.transa_quantity%>kg</h6>
                  <%if transa.transa_confirmation == false %>
                    <p class="text-grey">En attente confirmation producteur</p>
                  <%else%>
                    <p class="text-grey">Commande confirmé par le producteur</p>
                  <%end%>
                    <a href="<%=offer_transaction_path(transa.offer.id, transa.id)%>" role="button" class="button is-primary is-outlined">Voir les détails</a><br/><br/>
                </div>
            </div>     
          </div>
        <%end%> 
      <%end%> 
      </div>  
    </div>
  </div>  

<br/>

  <div class="container w-container">
    <div class="wrapper">
      <div class="shop-header">
        <h3 class="heading-7">Commandes passées</h3>
        <div class="shop-header-line">
          <div class="shop-header-color"></div>
        </div>
      </div>
    </div>

    <div class="columns w-row tabcontent">
      <div class="columns  is-multiline">
      <%current_buyer.transactions.each do |transa|%>
        <%if transa.transa_confirmation==true && transa.payment_confirmation ==true%>
          <div class="column is-one-third">
            <div class="product-card w-inline-block">
                <div class="product-card-image-wrapper"><img width="99" src="https://uploads-ssl.webflow.com/5d7e3127cad5177918ca3737/5d7e49b0a3db08f53036d9b4_lemon.svg" alt=""></div>
                <div class="card-content">
                  <h4 class="product-card-heading"><%=transa.offer.product.prod_name%></h4>
                  <h6 class="paragraph-2">Quantité commandée: <%=transa.transa_quantity%>kg</h6>
                  <%if transa.transa_confirmation == false %>
                    <p class="text-grey">En attente confirmation producteur</p>
                  <%else%>
                    <p class="text-grey">Commande confirmé</p>
                  <%end%>
                    <a href="<%=offer_transaction_path(transa.offer.id, transa.id)%>" role="button" class="button is-primary is-outlined">Voir les détails</a><br/><br/>
                </div>
            </div>     
          </div>
        <%end%>
      <%end%> 
      </div>  
    </div>
  </div>  