config/routes.rb
Rails.application.routes.draw do
  devise_for :buyers, controllers: { registrations: "registrations" }
  get 'static_pages/team'
  get 'static_pages/contact'
  root :to => "static_pages#home"
  get "/fetch_offers" => 'offers#from_category', as: 'fetch_offers'
  resources :offers, only: [:index] do
    resources :transactions
  end
  resources :buyers, only: [:show, :edit, :update]
  resource :messages do
    collection do
      post 'start'
      post 'confirm'
    end
  end
  resources :carts, only: [:show, :create, :edit]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_buyer!
  before_action :is_buyer_transa?, only: [:edit]

  def new
    @newtransaction=Transaction.new
    @offer=offer
    @same_offers=[]
    Offer.all.each do |offers|
      if (offers.product_id.nil? == false) && (offers.offer_quantity.nil? == false)
      if offers.product.prod_name ==  @offer.product.prod_name && offers!=@offer
        @same_offers << offer
      end
    end
    end
  end

  def create
    @offer=offer
    farmer = @offer.farmer
    transaction_params = params[:transaction]
    @newtransaction = Transaction.new(transa_adress: @offer.offer_adress,transa_zipcode: @offer.offer_zipcode, transa_quantity: transaction_params[:transa_quantity], transa_date: transaction_params[:transa_date], buyer_id: current_buyer.id, offer_id: params[:offer_id],transa_city: @offer.offer_city,transa_confirmation:false,payment_confirmation:false )

    if @newtransaction.save 
      new_quantity=@offer.offer_quantity-@newtransaction.transa_quantity
      @offer.update(:offer_quantity => new_quantity)
      flash[:primary] = "Produit ajouté au panier"
      redirect_to offers_path
    else
      render 'new'
    end
  end

  def show
    @transaction=transaction
    @offer=offer
  end

  def edit
    @transaction=transaction
    @offer=offer
    
  end

  def update
    if @transaction.update(transaction_update)
      flash[:sucess] = "Panier mis à jour"
      redirect_to buyer_path(current_buyer.id)
    else
      render 'edit'
    end
  end

  def destroy
    @transaction=transaction
    if @transaction.payment_confirmation==true 
      update_quantity
      @transaction.destroy
      #refund stripe
      flash[:success] = "Transaction supprimée, vous serez remboursé d'ici quelques jours"
    else
      update_quantity
      @transaction.destroy
      flash[:success] = "Panier mis à jour"
    end
    redirect_to buyer_path(current_buyer.id)
  end

  private
  def transaction_update
    params.require(:transaction).permit(:transa_date, :transa_quantity)
  end

  def transaction
    Transaction.find(params['id'])
  end

  def offer
    Offer.find(params[:offer_id])
  end

  def is_buyer_transa?
    if current_buyer.id!=transaction.buyer_id
      flash[:danger] = "Désolé cette page n'est pas accessible depuis votre profil, merci de vous connecter"
      redirect_to root_path
    end
  end  

  def update_quantity
    new_quantity=@transaction.offer.offer_quantity+@transaction.transa_quantity
    offer.update(:offer_quantity => new_quantity)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/edit.html.erb
  <ul>
    <% if @transaction.errors.any? %>    
      <div class="notification is-danger">                  
        <p>Nous n'avons pas réussi à modifier le potin pour la (ou les) raison(s) suivante(s) :</p>
        <% @transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </div>
    <% end %> 
  </ul>

<h1>Transactions#edit</h1>
<p>Find me in app/views/transactions/edit.html.erb</p>

<p>Adress : <%=@transaction.transa_adress%></p>
<p>Zipcode : <%=@transaction.transa_zipcode%></p>
<p>Ville : <%=@transaction.transa_city%></p>
<p>Quantité : <%=@transaction.transa_quantity%> kg</p>
<p>Date de rencontre : <%=@transaction.transa_date%></p>

<%= form_for @transaction, url: offer_transaction_path(params[:offer_id],params[:id]), html: {method: :patch} do |f| %>
    <%= f.label :Date_de_rencontre %><br />
    <%= f.date_field :transa_date, autofocus: true, autocomplete: "transa_date", min: @offer.date_harvest %><br /><br />

    <%= f.label :Quantité %><br />
    <%= f.number_field :transa_quantity, autofocus: true,in: 5..(@offer.offer_quantity+@transaction.transa_quantity), step: 5, autocomplete: "transa_quantity" %> kg <br /><br />
    <button type='submit'> Editer </button>
<%end%>
<a class="btn btn-warning" href="<%=offer_transaction_path(params[:offer_id],params[:id])%>" role="button" data-confirm="Etes-vous sur?" data-method="DELETE" >Annuler la Commande</a>

app/views/transactions/new.html.erb
<div></div>
  <div class="section-3">
    <div class="container-2 w-container">
      <div class="product">
              <div class="product-info">
                <h1 class="heading-3"><%=Product.find(@offer.product_id).prod_name%> <span> <%= image_tag("#{@offer.product.prod_name}.svg", width: "50px")%> </span> </h1>
                <p class="text-grey">Variété : <%=@offer.product.prod_subname.capitalize %></br>Quantité totale : <%=@offer.offer_quantity %>kg<br>Date de la récolte : <%=@offer.date_harvest.to_date.to_formatted_s(:long)  %><br>Lieu de la récolte : <%=@offer.offer_city%></p>
                <div class="product-price">Prix : <%=@offer.offer_price %> FCFA/kg</div>
                <div class="w-form">
                  <%= form_for @newtransaction, :url => "/offers/#{@offer.id}/transactions"  do |f| %>
                    <% if @newtransaction.errors.any? %> 
                      <div class="notification is-danger" >
                        <%= render "devise/shared/error_messages", resource: @newtransaction %>
                      </div>
                    <%end%>
                    <label class="label"><%= f.label :Date_de_rencontre %></label>
                    <%= f.date_field :transa_date, autofocus: true, autocomplete: "transa_date", min: @offer.date_harvest %><br /><br />
                    <%= f.label :Quantité %>
                    <%= f.number_field :transa_quantity, autofocus: true,in: 0..@offer.offer_quantity, step: 5, autocomplete: "transa_quantity" %> kg <br />
                    <button type='submit' class="button small w-button"> Ajouter au panier </button>
                  <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>

   <div class="container w-container">
    <div class="wrapper">
      <div class="shop-header">
        <h3 class="heading-7">Produits similaire</h3>
        <div class="shop-header-line">
          <div class="shop-header-color"></div>
        </div>
      </div>
    </div>

    <div class="columns w-row tabcontent">
      <div class="columns  is-multiline">
      <% if @same_offers!=nil%>
      <%@same_offers.each do |offer|%>
          <div class="column is-one-third">
            <div class="product-card w-inline-block">
                <div class="product-card-image-wrapper full-width" img width="99" alt=""> <%= image_tag "#{@offer.product.prod_name}.svg"%> </div>
                <div class="card-content">
                  <h4 class="product-card-heading"><%=Product.find(offer.product_id).prod_name%></h4>
                  <h6 class="paragraph-2">Quantité restante: <%=offer.offer_quantity %>kg</h6>
                  <h6 class="paragraph-2">Variété : <%=@offer.product.prod_subname.capitalize %></h6>
                  <h6 class="paragraph-2"> Ville: <%=offer.offer_city %></h6>
                  <h6 class="paragraph-2 bold">Prix : <%=offer.offer_price %> FCFA/kg</h6>
                  <a href="<%=new_offer_transaction_path(offer.id)%>" role="button" class="button is-primary is-outlined">Voir les détails</a>
                </div>
            </div>     
          </div>
      <%end%> 
      <%end%>
      </div>  
    </div>
  </div>  

app/views/transactions/show.html.erb
  <div class="section-4">
    <div class="container-2 w-container">
      <div class="product">
            <div class="product-info">
              <h1 class="heading-3"><%=@transaction.offer.product.prod_name%><span> <%= image_tag("#{@offer.product.prod_name}.svg", width: "50px")%></span></h1>
              <p class="text-grey"><br>‍<br>Date de la récolte : <%=@offer.date_harvest %><br><br>
              Date de rencontre : <%=@transaction.transa_date%><br><br>
              Lieu de l'échange : <%=@transaction.transa_adress%>, <%=@transaction.transa_city%>, <%=@transaction.transa_zipcode%><br>‍<br>
              Quantité achetée: <%=@transaction.transa_quantity%>kg<br>‍<br>
              Prix: <%=@transaction.transa_quantity*@offer.offer_price%>€</p>
              <a href="<%=edit_offer_transaction_path(@offer.id)%>" role="button" class="button is-primary is-outlined">Editer</a>
            </div>
      </div>
    </div>
  </div>