config/routes.rb
Rails.application.routes.draw do
  devise_for :buyers, controllers: { registrations: "registrations" }
  get 'static_pages/team'
  get 'static_pages/contact'
  root :to => "static_pages#home"
  get "/fetch_offers" => 'offers#from_category', as: 'fetch_offers'
  resources :offers, only: [:index] do
    resources :transactions
  end
  resources :buyers, only: [:show, :edit, :update]
  resource :messages do
    collection do
      post 'start'
      post 'confirm'
    end
  end
  resources :carts, only: [:show, :create, :edit]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_cart.html.erb
<%= link_to cart_path(current_buyer.id), class: "tag is-medium is-primary button_cart_nav" do %>
  <span><%= image_tag "shopping-cart.svg" %></span>
  <span class="badge"><%= @transa_cart %></span>
<% end %>

app/views/layouts/_footer1.html.erb
<div id="footergen1">
<div class="footer-distributed">

<div class="footer-left">

<%= image_tag "eden_logo_white.svg"%>

  <p class="footer-links"><b>
  <%= link_to "Accueil", root_path %>
    ·
    Blog
    ·
    A propos
    ·
    Faq
    ·
    Contact</b>
  </p></br>
</div>

<div class="footer-center">
<span>Coordonnées</span>
  <div>
    <p>21 Revolution Street </br> 75000 Paris, France</p>
  </div>

  <div>
    <p>contact@edenfarm.com</p></br></br></br>
  </div>

</div>

<div class="footer-right">

  <p class="footer-company-about">
    <span>À propos d'Eden</span>
    Eden permet aux agriculteurs des pays émergents d'avoir plus de visibilité auprès des acheteurs 
  </p>

  <div class="footer-icons">

    <a href="https://www.facebook.com/"><i class="fab fa-facebook-square"></i></a>
    <a href="https://twitter.com/"><i class="fab fa-twitter-square"></i></a>
    <a href="https://www.linkedin.com/"><i class="fab fa-linkedin"></i></a>
    <a href="https://www.youtube.com/?gl=FR&hl=fr"><i class="fab fa-youtube-square"></i></a>



  </div>

</div>

</div>

</div>

app/views/layouts/_footer2.html.erb
<div id="footergen2">
<%= image_tag "libra.svg" %>
<%= image_tag "visa.svg" %>
<%= image_tag "mastercard.svg" %>
<%= image_tag "americanexpress.svg" %></br></br>
   <b> © Eden. Tous droits réservés</b>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Eden</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css">

    <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <nav class="navbar topnav" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href='/offers'>
          <%= image_tag "eden_logo.svg"%>

        </a>
 
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false"onclick="showBurgerButton()">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <span  id="myLinks">
            <% if !current_buyer%>
              <div class="buttons">
                <%= link_to "Se connecter", new_buyer_session_path, class: "tag is-medium is-light"%>&nbsp;
                <%= link_to "S'inscrire", new_buyer_registration_path, class: "tag is-medium is-primary" %><br />
              </div>
            <%else%>
              <div class="buttons">
                <%= link_to "Mon Profil", buyer_path(current_buyer.id), class: "tag is-medium is-primary" %>&nbsp;
                <%= render partial: 'layouts/cart' %>&nbsp;
                <%= link_to "Se déconnecter", destroy_buyer_session_path, :data => {:confirm => 'Are you sure?'},:data => {:method => 'DELETE'}, class: "tag is-medium is-light" %><br />
              </div>
            <%end%>
      </span><br/>
      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item" href='/'>
            À propos
          </a>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <% if !current_buyer%>
              <div class="buttons">
                <%= link_to "Se connecter", new_buyer_session_path, class: "tag is-medium is-light"%>&nbsp;
                <%= link_to "S'inscrire", new_buyer_registration_path, class: "tag is-medium is-primary" %><br />
              </div>
            <%else%>
              <div class="buttons">
                <%= link_to "Mon Profil", buyer_path(current_buyer.id), class: "tag is-medium is-primary" %>&nbsp;
                <%= render partial: 'layouts/cart' %>&nbsp;
                <%= link_to "Se déconnecter", destroy_buyer_session_path, :data => {:confirm => 'Are you sure?'},:data => {:method => 'DELETE'}, class: "tag is-medium is-light" %><br />
              </div>
            <%end%>
          </div>
        </div>  
      </div>
    </nav>

    <% if flash %>
    <%flash.each do |name,msg|%>
      <div class="notification is-<%=name%>" id="hideonclick">
        <button class="delete" onclick="hideOnClick()
        "></button>
            <%= msg %>
      </div>
    <%end%>
    <% end %>

    <%= yield %>
    <%= csrf_meta_tags %>
    <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.4.1.min.220afd743d.js" type="text/javascript" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

    <%= render "layouts/footer1" %>
    <%= render "layouts/footer2" %>

  </body>
</html>